version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-autorizaciones}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  web:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@db:5432/autorizaciones}
      SECRET_KEY: ${SECRET_KEY:-supersecretkey}
      JWT_EXP_MINUTES: ${JWT_EXP_MINUTES:-4320}
    volumes:
      - ./backend/uploads:/app/uploads
      - ./frontend:/app/frontend:ro
    ports: ["8000:8000"]
    depends_on: [db]
volumes: { pgdata: {} }
